set(srcs "mosaico_game_2d.c" "mosaico_rgb565.c")
if(IDF_TARGET STREQUAL "esp32s31")
    list(APPEND srcs "mosaico_rgb565_pie.S")
endif()
idf_component_register(SRCS ${srcs} INCLUDE_DIRS "include" REQUIRES mosaico_game_assets raylib)
target_compile_options(${COMPONENT_LIB} PRIVATE -O3 -funroll-loops)
if(IDF_TARGET STREQUAL "esp32s31")
    target_compile_definitions(${COMPONENT_LIB} PRIVATE MOSAICO_RGB565_PIE=1)
endif()
