// SPDX-License-Identifier: Apache-2.0
/*
 * Shared entry point for examples that implement the Host game-module ABI.
 * The same game module is used by the host simulator and ELF package; native
 * builds compile it with MOSAICO_GAME_NATIVE and provide embedded assets.
 */
#include <stdlib.h>

#include "esp_err.h"
#include "esp_heap_caps.h"
#include "esp_log.h"
#include "raylib_lite_example_board.h"
#include "mosaico_game_assets.h"
#include "mosaico_game_module.h"
#include "raylib_lite_game_app.h"
#include "raylib_lite_native_hooks.h"

#ifndef MOSAICO_NATIVE_TARGET_FPS
#define MOSAICO_NATIVE_TARGET_FPS 0
#endif

static const char *TAG = "native_game";

/* Generated by raylib_lite_native_assets.cmake for each example. */
extern void raylib_lite_register_native_assets(void);

typedef struct {
    const mosaico_game_module_v1_t *module;
    void *state;
    raylib_lite_example_board_t *board;
    uint32_t last_render_error_log;
} native_game_t;

static raylib_lite_result_t to_runner_result(esp_err_t error)
{
    switch (error) {
    case ESP_OK: return RAYLIB_LITE_OK;
    case ESP_ERR_INVALID_ARG: return RAYLIB_LITE_INVALID_ARGUMENT;
    case ESP_ERR_INVALID_STATE: return RAYLIB_LITE_INVALID_STATE;
    case ESP_ERR_NO_MEM: return RAYLIB_LITE_NO_MEMORY;
    case ESP_ERR_TIMEOUT: return RAYLIB_LITE_TIMEOUT;
    case ESP_ERR_NOT_SUPPORTED: return RAYLIB_LITE_NOT_SUPPORTED;
    default: return RAYLIB_LITE_PLATFORM_ERROR;
    }
}

static esp_err_t to_esp_result(raylib_lite_result_t result)
{
    switch (result) {
    case RAYLIB_LITE_OK: return ESP_OK;
    case RAYLIB_LITE_INVALID_ARGUMENT: return ESP_ERR_INVALID_ARG;
    case RAYLIB_LITE_INVALID_STATE: return ESP_ERR_INVALID_STATE;
    case RAYLIB_LITE_NO_MEMORY: return ESP_ERR_NO_MEM;
    case RAYLIB_LITE_TIMEOUT: return ESP_ERR_TIMEOUT;
    case RAYLIB_LITE_NOT_SUPPORTED: return ESP_ERR_NOT_SUPPORTED;
    default: return ESP_FAIL;
    }
}

static raylib_lite_result_t game_start(void *user)
{
    native_game_t *game = user;
    raylib_lite_register_native_assets();

    game->state = heap_caps_calloc(1, game->module->state_size,
                                   MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
    if (!game->state) {
        /* Some modules fit in internal RAM on boards without PSRAM. */
        game->state = heap_caps_calloc(1, game->module->state_size,
                                       MALLOC_CAP_8BIT);
    }
    if (!game->state) return RAYLIB_LITE_NO_MEMORY;

    if (game->module->initialize(game->state, NULL) != 0) {
        ESP_LOGE(TAG, "game module initialization failed");
        return RAYLIB_LITE_PLATFORM_ERROR;
    }
    return RAYLIB_LITE_OK;
}

static raylib_lite_result_t first_present(void *user)
{
    native_game_t *game = user;
    esp_err_t error = raylib_lite_example_board_start_input(game->board);
    if (error != ESP_OK) {
        ESP_LOGE(TAG, "start board input: %s", esp_err_to_name(error));
        return to_runner_result(error);
    }
    raylib_lite_native_first_present();
    return RAYLIB_LITE_OK;
}

static void game_event(void *user, const raylib_lite_input_event_t *event)
{
    native_game_t *game = user;
    if (!event || !game->module->input) return;

    mosaico_host_input_v1_t input = {0};
    switch (event->type) {
    case RAYLIB_LITE_INPUT_POINTER:
    case RAYLIB_LITE_INPUT_TOUCH:
        input.type = MOSAICO_HOST_INPUT_POINTER;
        input.x = event->x;
        input.y = event->y;
        input.track_id = event->type == RAYLIB_LITE_INPUT_TOUCH
            ? event->value : 0;
        input.pressed = event->pressed;
        break;
    case RAYLIB_LITE_INPUT_BUTTON:
        input.type = MOSAICO_HOST_INPUT_ACTION;
        input.code = event->value;
        input.pressed = event->pressed;
        break;
    case RAYLIB_LITE_INPUT_IMU:
        input.type = MOSAICO_HOST_INPUT_IMU;
        input.value_x = event->x / 1000.0f;
        input.value_y = event->y / 1000.0f;
        input.value_z = event->value / 1000.0f;
        break;
    default:
        return;
    }
    game->module->input(game->state, &input);
}

static void game_update(void *user)
{
    native_game_t *game = user;
    if (game->module->update) game->module->update(game->state);
}

static void game_render(void *user)
{
    native_game_t *game = user;
    if (!game->module->render) return;
    int result = game->module->render(game->state);
    if (result != 0 && game->last_render_error_log++ == 0)
        ESP_LOGE(TAG, "game module render returned %d", result);
}

static void game_stats(void *user)
{
    native_game_t *game = user;
    if (game->module->state_hash)
        ESP_LOGI(TAG, "%s state=%08lx",
                 game->module->descriptor.game_id,
                 (unsigned long)game->module->state_hash(game->state));
}

static void game_stop(void *user)
{
    native_game_t *game = user;
    if (game->state && game->module->shutdown)
        game->module->shutdown(game->state);
    heap_caps_free(game->state);
    game->state = NULL;
    mosaico_game_assets_unmount();
}

static esp_err_t cleanup_board(raylib_lite_example_board_t *board)
{
    if (!board) return ESP_OK;
    esp_err_t error = raylib_lite_example_board_stop(board, 3000);
    if (error != ESP_OK && error != ESP_ERR_INVALID_STATE)
        ESP_LOGW(TAG, "stop board input: %s", esp_err_to_name(error));
    error = raylib_lite_example_board_destroy(board, 3000);
    if (error == ESP_OK) return ESP_OK;
    ESP_LOGW(TAG, "destroy board: %s; retrying cleanup", esp_err_to_name(error));
    return raylib_lite_example_board_retry_cleanup(board, 3000);
}

void app_main(void)
{
    if (!raylib_lite_native_boot()) {
        ESP_LOGE(TAG, "native startup hook failed");
        return;
    }

    const raylib_lite_example_board_config_t board_config = {
        .touch_points = 2,
        .enable_imu = true,
        .imu_sample_ms = 20,
        .drawbuf_lines = 34,
        .drawbuf_count = 2,
    };
    raylib_lite_example_board_t *board = NULL;
    esp_err_t error = raylib_lite_example_board_create(&board_config, &board);
    if (error != ESP_OK) {
        ESP_LOGE(TAG, "create board platform: %s", esp_err_to_name(error));
        if (board)
            (void)raylib_lite_example_board_retry_cleanup(board, 3000);
        return;
    }

    const mosaico_game_module_v1_t *module = mosaico_game_module_v1();
    if (!module || !module->descriptor.game_id || !module->state_size ||
            !module->initialize || !module->render) {
        ESP_LOGE(TAG, "game module descriptor is incomplete");
        (void)cleanup_board(board);
        return;
    }

    native_game_t game = {.module = module, .board = board};
    const uint32_t logic_hz = module->descriptor.tick_hz
        ? module->descriptor.tick_hz : 30;
    const uint32_t target_fps = MOSAICO_NATIVE_TARGET_FPS
        ? MOSAICO_NATIVE_TARGET_FPS : logic_hz;
    const raylib_lite_platform_t *services =
        raylib_lite_example_board_services(board);
    if (!services) {
        ESP_LOGE(TAG, "board platform has no services");
        (void)cleanup_board(board);
        return;
    }
    const raylib_lite_game_app_t app = {
        .tag = module->descriptor.game_id,
        .window_title = module->descriptor.title,
        .logic_hz = logic_hz,
        .target_fps = target_fps,
        .stats_interval = logic_hz * 10,
        .platform = *services,
        .input = raylib_lite_example_board_input(board),
        .user = &game,
        .on_start = game_start,
        .on_first_present = first_present,
        .on_event = game_event,
        .on_update = game_update,
        .on_render = game_render,
        .on_stats = game_stats,
        .on_stop = game_stop,
    };
    error = to_esp_result(raylib_lite_game_app_run(&app));
    if (error != ESP_OK) ESP_LOGE(TAG, "game stopped: %s", esp_err_to_name(error));
    esp_err_t cleanup = cleanup_board(board);
    if (cleanup != ESP_OK)
        ESP_LOGE(TAG, "board cleanup failed: %s", esp_err_to_name(cleanup));
}
