// SPDX-License-Identifier: Apache-2.0
#include "mosaico_game_save.h"
#include "nvs.h"
#include <string.h>
typedef struct { uint32_t magic;uint16_t version,size;uint32_t crc;uint8_t data[MOSAICO_SAVE_MAX_PAYLOAD]; } save_blob_t;
#define SAVE_MAGIC UINT32_C(0x3156534d)
#define SAVE_HEADER_SIZE offsetof(save_blob_t,data)
static uint32_t crc32(const void *data,size_t size){uint32_t c=~0U;const uint8_t *p=data;while(size--){c^=*p++;for(int i=0;i<8;++i)c=(c>>1)^(0xedb88320U&-(int32_t)(c&1));}return ~c;}
esp_err_t mosaico_save_init(mosaico_save_t *s,const mosaico_save_config_t *c){if(!s||!c||!c->nvs_namespace||!c->key||!c->payload_size||c->payload_size>MOSAICO_SAVE_MAX_PAYLOAD)return ESP_ERR_INVALID_ARG;memset(s,0,sizeof(*s));s->config=*c;s->initialized=true;return ESP_OK;}
esp_err_t mosaico_save_load(mosaico_save_t *s,void *payload,const void *defaults){if(!s||!s->initialized||!payload)return ESP_ERR_INVALID_STATE;if(defaults)memcpy(payload,defaults,s->config.payload_size);else memset(payload,0,s->config.payload_size);nvs_handle_t h;esp_err_t e=nvs_open(s->config.nvs_namespace,NVS_READONLY,&h);if(e==ESP_ERR_NVS_NOT_FOUND)return ESP_OK;if(e!=ESP_OK)return e;save_blob_t v;size_t size=sizeof(v);e=nvs_get_blob(h,s->config.key,&v,&size);nvs_close(h);if(e==ESP_ERR_NVS_NOT_FOUND)return ESP_OK;if(e!=ESP_OK)return e;if(size<SAVE_HEADER_SIZE||v.size>MOSAICO_SAVE_MAX_PAYLOAD||SAVE_HEADER_SIZE+v.size!=size)return ESP_ERR_INVALID_CRC;if(v.magic!=SAVE_MAGIC||crc32(v.data,v.size)!=v.crc)return ESP_ERR_INVALID_CRC;if(v.version==s->config.version&&v.size==s->config.payload_size){memcpy(payload,v.data,v.size);return ESP_OK;}return s->config.migrate?s->config.migrate(v.version,v.data,v.size,payload,s->config.payload_size):ESP_ERR_INVALID_VERSION;}
esp_err_t mosaico_save_request(mosaico_save_t *s,const void *p,uint64_t now){if(!s||!s->initialized||!p)return ESP_ERR_INVALID_ARG;memcpy(s->pending,p,s->config.payload_size);s->due_ms=now+s->config.debounce_ms;s->dirty=true;return ESP_OK;}
esp_err_t mosaico_save_flush(mosaico_save_t *s,uint64_t now,bool force){if(!s||!s->initialized)return ESP_ERR_INVALID_STATE;if(!s->dirty||(!force&&now<s->due_ms))return ESP_OK;save_blob_t v={.magic=SAVE_MAGIC,.version=s->config.version,.size=(uint16_t)s->config.payload_size,.crc=crc32(s->pending,s->config.payload_size)};memcpy(v.data,s->pending,s->config.payload_size);nvs_handle_t h=0;esp_err_t e=nvs_open(s->config.nvs_namespace,NVS_READWRITE,&h);if(e==ESP_OK)e=nvs_set_blob(h,s->config.key,&v,SAVE_HEADER_SIZE+s->config.payload_size);if(e==ESP_OK)e=nvs_commit(h);if(e==ESP_OK)s->dirty=false;if(h)nvs_close(h);return e;}
