# Optional local BSP checkout for native example development.
if(NOT RAYLIB_LITE_BSP_DIR AND DEFINED ENV{RAYLIB_LITE_BSP_DIR})
    set(RAYLIB_LITE_BSP_DIR "$ENV{RAYLIB_LITE_BSP_DIR}")
endif()
function(_raylib_lite_add_local_component root component)
    if(EXISTS "${root}/CMakeLists.txt" AND EXISTS "${root}/idf_component.yml")
        get_filename_component(_local_name "${root}" NAME)
        if(NOT _local_name STREQUAL component)
            message(FATAL_ERROR "Expected local component ${component}, got ${root}")
        endif()
        list(APPEND EXTRA_COMPONENT_DIRS "${root}")
        set(EXTRA_COMPONENT_DIRS "${EXTRA_COMPONENT_DIRS}" PARENT_SCOPE)
        return()
    endif()
    if(EXISTS "${root}/${component}/CMakeLists.txt")
        list(APPEND EXTRA_COMPONENT_DIRS "${root}/${component}")
        set(EXTRA_COMPONENT_DIRS "${EXTRA_COMPONENT_DIRS}" PARENT_SCOPE)
        return()
    endif()
    message(FATAL_ERROR
        "Local component ${component} was not found under ${root}")
endfunction()

if(RAYLIB_LITE_BSP_DIR)
    set(_raylib_lite_bsp "${RAYLIB_LITE_BSP_DIR}")
    set(_raylib_lite_splash "")
    if(EXISTS "${_raylib_lite_bsp}/components/esp-mosaico-bsp/CMakeLists.txt")
        set(_raylib_lite_splash "${_raylib_lite_bsp}/components/mosaico_boot_splash")
        set(_raylib_lite_bsp "${_raylib_lite_bsp}/components")
    elseif(EXISTS "${_raylib_lite_bsp}/CMakeLists.txt")
        get_filename_component(_raylib_lite_splash "${_raylib_lite_bsp}" DIRECTORY)
        set(_raylib_lite_splash "${_raylib_lite_splash}/mosaico_boot_splash")
    endif()
    _raylib_lite_add_local_component("${_raylib_lite_bsp}" "esp-mosaico-bsp")
    if(EXISTS "${_raylib_lite_splash}/CMakeLists.txt")
        list(APPEND EXTRA_COMPONENT_DIRS "${_raylib_lite_splash}")
    endif()
endif()
