# ESP-IDF integration for Raylib Lite Engine.
get_filename_component(RAYLIB_LITE_ENGINE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

function(mosaico_game_sdk_add_components)
    set(options RAYLIB AUDIO TILEMAP SCENE UI FX SAVE)
    cmake_parse_arguments(GAME "${options}" "" "" ${ARGN})

    set(_components mosaico_game mosaico_game_input mosaico_game_debug)
    if(GAME_RAYLIB OR GAME_AUDIO OR GAME_TILEMAP)
        list(APPEND _components mosaico_game_assets)
    endif()
    if(GAME_RAYLIB OR GAME_AUDIO)
        list(APPEND _components raylib_lite_platform)
    endif()
    if(GAME_RAYLIB OR GAME_TILEMAP)
        list(APPEND _components mosaico_game_2d)
    endif()
    if(GAME_RAYLIB)
        list(APPEND _components raylib_lite_runner mosaico_raylib_fast
             mosaico_raylib_port mosaico_game_app)
    endif()
    if(GAME_TILEMAP)
        list(APPEND _components mosaico_game_tilemap)
    endif()
    if(GAME_SCENE)
        list(APPEND _components mosaico_game_scene)
    endif()
    if(GAME_UI)
        list(APPEND _components mosaico_game_ui)
    endif()
    if(GAME_FX)
        list(APPEND _components mosaico_game_fx)
    endif()
    if(GAME_SAVE)
        list(APPEND _components mosaico_game_save)
    endif()

    foreach(_component IN LISTS _components)
        list(APPEND EXTRA_COMPONENT_DIRS
            "${RAYLIB_LITE_ENGINE_ROOT}/components/${_component}")
    endforeach()
    list(REMOVE_DUPLICATES EXTRA_COMPONENT_DIRS)
    set(EXTRA_COMPONENT_DIRS "${EXTRA_COMPONENT_DIRS}" PARENT_SCOPE)
endfunction()
